Lets see what this does to support multiple fallbacks...

diff --git a/trunk/scriptlets.d/acpi_sleep b/trunk/scriptlets.d/acpi_sleep
--- a/trunk/scriptlets.d/acpi_sleep
+++ b/trunk/scriptlets.d/acpi_sleep
@@ -15,6 +15,12 @@ ACPI_SLEEP_FILE=/proc/acpi/sleep
 ACPISleepConfigEnabler() {
     [ "$1" != "useacpisleep" ] && return 1
     [ -n "$USING_ACPI_SLEEP" ] && return 0
+    if [ -n "$NO_COMPLAIN_UNSUPPORTED" ] ; then
+	# Just bail silently if we don't detect it.
+	if ! test -f $ACPI_SLEEP_FILE ; then
+	    return 0
+	fi
+    fi
     UsingSuspendMethod acpi_sleep
     AddSuspendHook 10 EnsureACPISleepCapable
     AddSuspendHook 99 DoACPISleep
diff --git a/trunk/scriptlets.d/suspend2 b/trunk/scriptlets.d/suspend2
--- a/trunk/scriptlets.d/suspend2
+++ b/trunk/scriptlets.d/suspend2
@@ -66,6 +66,10 @@ Swsusp2ConfigEnabler() {
     [ "$1" != "usesuspend2" ] && [ "$1" != "useswsusp2" ] && return 1
     BoolIsOn "$1" "$2" || return 0
     [ -n "$USING_SWSUSP2" ] && return 0
+    if [ -n "$NO_COMPLAIN_UNSUPPORTED" ] ; then
+	# Just bail silently if we don't detect it.
+	[ -d "$SWSUSP_ROOT" ] || return 0
+    fi
     UsingSuspendMethod suspend2
     AddConfigHandler Swsusp2ConfigOptions
     AddSuspendHook 10 EnsureSwsusp2Capable
diff --git a/trunk/scriptlets.d/sysfs_power_state b/trunk/scriptlets.d/sysfs_power_state
--- a/trunk/scriptlets.d/sysfs_power_state
+++ b/trunk/scriptlets.d/sysfs_power_state
@@ -18,6 +18,12 @@ SYSFS_POWERDOWN_METHOD_FILE=/sys/power/disk
 SysfsPowerStateConfigEnabler() {
     [ "$1" != "usesysfspowerstate" ] && return 1
     [ -n "$USING_SYSFS_POWER_STATE" ] && return 0
+    if [ -n "$NO_COMPLAIN_UNSUPPORTED" ] ; then
+	# Just bail silently if we don't detect it.
+	if ! test -f $SYSFS_POWER_STATE_FILE || ! grep -q $2 $SYSFS_POWER_STATE_FILE ; then
+	    return 0
+	fi
+    fi
     UsingSuspendMethod sysfs_power_state
     AddConfigHandler SysfsPowerStateConfigOptions
     AddSuspendHook 10 EnsureSysfsPowerStateCapable
