Installer script cleanups. Honour the  environment variable. Promote ubuntu.

diff --git a/trunk/scriptlets.d/clock b/trunk/scriptlets.d/clock
--- a/trunk/scriptlets.d/clock
+++ b/trunk/scriptlets.d/clock
@@ -5,24 +5,30 @@ AddConfigHandler ClockOptions
 AddConfigHelp "SaveClock restore-only|<boolean>" "Set this to yes to save the system clock before suspending and restore the system clock after resuming. If set to restore-only, the clock will not be saved, only restored - this means suspending is faster, but if your hardware clock drifts significantly, your system clock will drift as well."
 
 ClockSave() {
-    if [ "x$DISTRIBUTION" = "xdebian" ] ; then
-	/etc/init.d/hwclock.sh stop > /dev/null 2>&1
-    else
-	if ! /sbin/hwclock --systohc ; then
-	    echo "$EXE: Failed to save system clock - continuing anyway"
-	fi
-    fi
+    case "$DISTRIBUTION" in
+	debian|ubuntu)
+	    /etc/init.d/hwclock.sh stop > /dev/null 2>&1
+	    ;;
+	*)
+	    if ! /sbin/hwclock --systohc ; then
+		echo "$EXE: Failed to save system clock - continuing anyway"
+	    fi
+	    ;;
+    esac
     return 0  # clock save failing shouldn't be a show stopper, ever.
 }
 
 ClockRestore() {
-    if [ "x$DISTRIBUTION" = "xdebian" ] ; then
-	/etc/init.d/hwclock.sh start > /dev/null 2>&1
-    else
-	if ! /sbin/hwclock --hctosys ; then
-	    echo "$EXE: Failed to restore system clock."
-	fi
-    fi
+    case "$DISTRIBUTION" in
+	debian|ubuntu)
+	    /etc/init.d/hwclock.sh start > /dev/null 2>&1
+	    ;;
+	*)
+	    if ! /sbin/hwclock --hctosys ; then
+		echo "$EXE: Failed to restore system clock."
+	    fi
+	    ;;
+    esac
     # exit code unchanged.
 }
 
