- Improved ususpend method. Now supports USuspendRamForce (boolean) to     pass the -f option to s2ram. Also tests with s2ram's -n option if s2ram     is used and the option is not set. I also made disk.conf and ram.conf     prefer the uswsusp methods, if they are available. If you do not want to     use them, use the sysfs-{ram,disk}.conf files, which are the former     ram.conf and disk.conf files.

diff --git a/trunk/scriptlets.d/ususpend b/trunk/scriptlets.d/ususpend
--- a/trunk/scriptlets.d/ususpend
+++ b/trunk/scriptlets.d/ususpend
@@ -4,38 +4,61 @@
 AddConfigHandler USuspendConfigEnabler
 AddOptionHandler USuspendOptionHandler
 
-AddConfigHelp "UseUSuspend <boolean>" "If enabled, uses the 's2disk' program to suspend the machine with uswsusp."
+AddConfigHelp "USuspendMethod <disk|ram|both>" "Enables use of the uswsusp suspend method of newer kernels (>= 2.6.17rc1)"
+AddConfigHelp "USuspendRamForce <boolean>" "Passes the -f flag to s2ram to force suspending even if the machine is not recognised"
 
 AddShortOption "n"
 AddLongOption "no-suspend"
 
-USUSPEND_PROG=s2disk
 USUSPEND_STATE_FILE=/sys/power/state
 USUSPEND_DEVICE=/dev/snapshot
+USUSPEND_PROG=s2disk
+USUSPEND_RAM_FORCE=0
 
 USuspendConfigEnabler() {
-    [ "$1" != "useususpend" ] && return 1
-    BoolIsOn "$1" "$2" || return 0
-    [ -n "$USING_USUSPEND_STATE" ] && return 0
-    if [ -n "$NO_COMPLAIN_UNSUPPORTED" ] ; then
-	# Just bail silently if we don't detect it.
-	if ! test -f $USUSPEND_STATE_FILE || ! test -c $USUSPEND_DEVICE ||
-	   ! command -v $USUSPEND_PROG > /dev/null 2>&1 ; then
-	    return 0
-	fi
+    case "$1" in
+	ususpendmethod)
+	    case "$2" in
+		disk|both) USUSPEND_PROG=s2$2;;
+		ram)
+		    USUSPEND_PROG=s2ram
+		    ;;
+		*)
+		    vecho 1 "$EXE: Invalid value fo USuspendMethod."
+		    return 2
+		    ;;
+	    esac
+
+	    if [ -n "$NO_COMPLAIN_UNSUPPORTED" ] ; then
+		# Just bail silently if we don't detect it.
+		if ! test -f $USUSPEND_STATE_FILE || ! test -c $USUSPEND_DEVICE ||
+		    ! command -v $USUSPEND_PROG > /dev/null 2>&1 ; then
+		    return 0
+		fi
+	    fi
+	    ;;
+
+	ususpendramforce)
+	    BoolIsOn "$1" "$2" && USUSPEND_RAM_FORCE=1 || return 0
+	    ;;
+	    
+	*) return 1;;
+    esac
+
+    if [ -z "$USUSPEND_HOOKED" ]; then
+	UsingSuspendMethod ususpend
+	AddSuspendHook 10 EnsureUSuspendCapable
+	AddSuspendHook 99 DoUSuspend
+	USUSPEND_HOOKED=1
     fi
-    UsingSuspendMethod ususpend
-    AddSuspendHook 10 EnsureUSuspendCapable
-    AddSuspendHook 99 DoUSuspend
-    USING_USUSPEND_STATE=1
     return 0
 }
 
 USuspendOptionHandler() {
-    [ -z "$USING_USUSPEND_STATE" ] && return 1
+    [ -z "$USUSPEND_HOOKED" ] && return 1
     case $1 in
 	-n|--no-suspend)
-	    USUSPEND_STATE_NO_SUSPEND=1
+	    USUSPEND_NO_SUSPEND=1
 	    ;;
 	*)
 	    return 1
@@ -44,9 +67,12 @@ USuspendOptionHandler() {
 }
 
 DoUSuspend() {
-    if [ -z "$USUSPEND_STATE_NO_SUSPEND" ] ; then
-	vecho 1 "$EXE: Running $USUSPEND_PROG_PATH ..."
-	$USUSPEND_PROG_PATH || vecho 0 "$EXE: $USUSPEND_PROG_PATH failed."
+    if [ -z "$USUSPEND_NO_SUSPEND" ] ; then
+	vecho 1 "$EXE: Running $USUSPEND_PROG_PATH ${FORCE:+$FORCE }..."
+	[ "$USUSPEND_PROG" = s2ram ] && [ $USUSPEND_RAM_FORCE -eq 1 ] \
+	    && FORCE=-f
+	$USUSPEND_PROG_PATH $FORCE 2>&1 | vcat 2 \
+	    || vecho 0 "$EXE: $USUSPEND_PROG_PATH failed."
     else
 	vecho 1 "$EXE: Not actually suspending (--no-suspend given)."
     fi
@@ -56,6 +82,11 @@ DoUSuspend() {
 EnsureUSuspendCapable() {
     if ! USUSPEND_PROG_PATH=$(command -v $USUSPEND_PROG) ; then
 	vecho 0 "$USUSPEND_PROG not installed."
+	return 2
+    fi
+    if [ "$USUSPEND_PROG" = s2ram ] && [ $USUSPEND_RAM_FORCE -eq 0 ] \
+	    && ! $USUSPEND_PROG -n >/dev/null; then
+	vecho 0 "$USUSPEND_PROG: unknown machine, see s2ram(8) and the USuspendRamForce option"
 	return 2
     fi
     if ! test -f $USUSPEND_STATE_FILE ; then
